INSERT INTO `tbl_promo_event`
	(`title`, `slug`, `type`, `short_description`, `content`, `image`, `location`, `start_date`, `end_date`, `button_text`, `button_url`, `is_featured`, `display_order`, `status`)
VALUES
	(
		'Bonus Voucher Belanja Rp50.000',
		'bonus-voucher-belanja-50000',
		'Promo Pembayaran',
		'Dapatkan voucher belanja Rp50.000 untuk transaksi minimum Rp500.000 menggunakan kartu pembayaran pilihan.',
		'<p>Nikmati <strong>bonus voucher belanja Rp50.000</strong> untuk transaksi minimum Rp500.000 di Manna Kampus.</p><p>Promo berlaku untuk metode pembayaran pilihan dan tidak dapat digabungkan dengan program diskon lainnya. Kuota promo tersedia setiap hari selama periode program.</p>',
		'promo-payment-voucher.webp',
		'Seluruh outlet Manna Kampus',
		'2026-07-01',
		'2026-12-31',
		'Lihat Ketentuan',
		'promo-event/bonus-voucher-belanja-50000',
		1,
		1,
		'Active'
	),
	(
		'Cashback Dompet Digital 10%',
		'cashback-dompet-digital-10-persen',
		'Promo Pembayaran',
		'Bayar menggunakan dompet digital pilihan dan dapatkan cashback 10% hingga Rp75.000.',
		'<p>Dapatkan <strong>cashback 10% hingga Rp75.000</strong> untuk pembayaran menggunakan dompet digital pilihan.</p><p>Cashback diberikan sesuai ketentuan penyedia pembayaran dan kuota yang tersedia. Pastikan aplikasi pembayaran sudah diperbarui sebelum melakukan transaksi.</p>',
		'promo-payment-wallet.webp',
		'Seluruh outlet Manna Kampus',
		'2026-07-01',
		'2026-12-31',
		'Lihat Ketentuan',
		'promo-event/cashback-dompet-digital-10-persen',
		1,
		2,
		'Active'
	),
	(
		'Potongan Kartu Kredit Rp80.000',
		'potongan-kartu-kredit-80000',
		'Promo Pembayaran',
		'Nikmati potongan langsung Rp80.000 dengan minimum transaksi Rp800.000 menggunakan kartu kredit pilihan.',
		'<p>Nikmati <strong>potongan langsung Rp80.000</strong> dengan minimum transaksi Rp800.000 menggunakan kartu kredit pilihan.</p><p>Promo berlaku satu kali per nasabah per hari dan mengikuti kuota yang tersedia. Syarat serta ketentuan masing-masing penerbit kartu tetap berlaku.</p>',
		'promo-payment-card.webp',
		'Seluruh outlet Manna Kampus',
		'2026-07-01',
		'2026-12-31',
		'Lihat Ketentuan',
		'promo-event/potongan-kartu-kredit-80000',
		1,
		3,
		'Active'
	)
ON DUPLICATE KEY UPDATE
	`title` = VALUES(`title`),
	`type` = VALUES(`type`),
	`short_description` = VALUES(`short_description`),
	`content` = VALUES(`content`),
	`image` = VALUES(`image`),
	`location` = VALUES(`location`),
	`start_date` = VALUES(`start_date`),
	`end_date` = VALUES(`end_date`),
	`button_text` = VALUES(`button_text`),
	`button_url` = VALUES(`button_url`),
	`is_featured` = VALUES(`is_featured`),
	`display_order` = VALUES(`display_order`),
	`status` = VALUES(`status`);
